-- Reference data for the Supabase swap. The 15 demo projects, their stage
-- history, escalations and chat threads are generated by src/lib/db/seed.ts,
-- which produces dates relative to "today" — port it by replaying the same
-- specs through the RPC functions rather than hard-coding timestamps here.

insert into departments (code, name) values
  ('MIN',  'Ministry (CMO)'),
  ('FIN',  'Finance Department'),
  ('RB',   'Roads & Buildings (PWD)'),
  ('TND',  'Tender Cell'),
  ('SITE', 'Site Execution Wing');

insert into districts (code, name) values
  ('AHD', 'Ahmedabad'),
  ('VAD', 'Vadodara'),
  ('SRT', 'Surat');

insert into desks (department_id, designation, officer_name, phone, email)
select d.id, x.designation, x.officer_name, x.phone, x.email
from (values
  ('MIN',  'Section Officer (CMO)',      'R. Mehta',   '079-2325-1101', 'so.cmo@gujarat.gov.in'),
  ('MIN',  'Deputy Secretary (CMO)',     'A. Bhatt',   '079-2325-1102', 'ds.cmo@gujarat.gov.in'),
  ('FIN',  'Section Officer (Finance)',  'K. Patel',   '079-2325-2201', 'so.fin@gujarat.gov.in'),
  ('FIN',  'Accounts Officer',           'S. Desai',   '079-2325-2202', 'ao.fin@gujarat.gov.in'),
  ('FIN',  'Planning Officer',           'M. Joshi',   '079-2325-2203', 'plan.fin@gujarat.gov.in'),
  ('FIN',  'Deputy Secretary (Finance)', 'P. Shah',    '079-2325-2204', 'ds.fin@gujarat.gov.in'),
  ('FIN',  'Secretary (Finance)',        'V. Trivedi', '079-2325-2205', 'sec.fin@gujarat.gov.in'),
  ('RB',   'Junior Engineer',            'H. Solanki', '079-2325-3301', 'je.rb@gujarat.gov.in'),
  ('RB',   'Deputy Engineer',            'N. Chauhan', '079-2325-3302', 'de.rb@gujarat.gov.in'),
  ('RB',   'Executive Engineer',         'D. Rathod',  '079-2325-3303', 'ee.rb@gujarat.gov.in'),
  ('RB',   'Superintending Engineer',    'J. Vyas',    '079-2325-3304', 'se.rb@gujarat.gov.in'),
  ('RB',   'Chief Engineer',             'B. Parmar',  '079-2325-3305', 'ce.rb@gujarat.gov.in'),
  ('TND',  'Tender Clerk',               'F. Qureshi', '079-2325-4401', 'clerk.tnd@gujarat.gov.in'),
  ('TND',  'Tender Officer',             'L. Pandya',  '079-2325-4402', 'officer.tnd@gujarat.gov.in'),
  ('SITE', 'Site Engineer',              'T. Makwana', '079-2325-5501', 'site.eng@gujarat.gov.in'),
  ('SITE', 'EE (Site Wing)',             'G. Thakkar', '079-2325-5502', 'ee.site@gujarat.gov.in')
) as x(dept, designation, officer_name, phone, email)
join departments d on d.code = x.dept;

insert into stage_definitions (key, seq, name, owner_department_id, default_sla_days)
select x.key::stage_key, x.seq, x.name, d.id, x.sla
from (values
  ('MINISTRY_PROPOSAL', 1, 'Ministry Proposal',                        'MIN',  15),
  ('ADMIN_APPROVAL',    2, 'Administrative Approval + Fund Allotment', 'FIN',  21),
  ('TECH_SANCTION',     3, 'Technical Sanction',                       'RB',   21),
  ('TENDER',            4, 'Tender (nProcure)',                        'TND',  45),
  ('WORK_ORDER',        5, 'Work Order',                               'RB',    7),
  ('SITE_EXECUTION',    6, 'Site Execution',                           'SITE',180),
  ('COMPLETION_REPORT', 7, 'Completion Report',                        'RB',   15),
  ('FINAL_BILL',        8, 'Final Bill',                               'FIN',  30),
  ('DLP_CLOSURE',       9, 'Defect Liability Period & Closure',        'RB',  365)
) as x(key, seq, name, dept, sla)
join departments d on d.code = x.dept;

-- Demo users: create them in Supabase Auth first (password Demo@1234), then
-- insert the matching profiles rows keyed by the auth user id:
--   ministry@demo · finance.head@demo · finance.op@demo · rb.head@demo
--   rb.op@demo · tender.head@demo · site.head@demo · site.eng@demo · admin@demo
